---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app: kismet
  name: kismet-ingress
spec:
  rules:
  - host: kismet.k3s.sketchybinary.com
    http:
      paths:
      - backend:
          serviceName: kismet-service
          servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: kismet-service
  namespace: default
spec:
  selector:
    app: kismet
  ports:
  - protocol: TCP
    port: 2501
    name: http
  - protocol: TCP
    port: 3501
    name: api

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kismet
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kismet
  template:
    metadata:
      labels:
        app: kismet
    spec:
      containers:
      - image: quay.io/sketchybinary/kismet
        name: kismet
        ports:
        - containerPort: 3501
          name: api
        - containerPort: 2501
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 3
---
